baseURL = 'http://example.org/'
languageCode = 'fr-FR'
title = 'Les actus de bob'
theme = 'PaperMod'

[params]
author = "Bob"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true

[params.homeInfoParams]
Title = "Bienvue sur le site des actus de Bob"
Content = "Tout a commencé un jour où j'ai partagé des fun fact sur les [vers de terre](/posts/01-vers-de-terre/) avec mes amis sur Discord, et cela a suscité un tel engouement que j'ai décidé d'écrire un article par jour sur des sujets aléatoires. Ici, vous trouverez une collection croissante de mes actus."

[[params.socialIcons]]
name = "github"
url = "https://github.com/Paracetamol56/actu-de-bob"

[outputs]
home = [ "HTML", "RSS", "JSON" ]